version: 0.0
os: linux
files:
  - source: ./dist/
    destination: /home/ubuntu/ida-accounts/dist/

  - source: ./ida-accounts/package.json
    destination: /home/ubuntu/ida-accounts/
 
  - source: ./ida-accounts/server-files/ida-accounts.service
    destination: /lib/systemd/system/

  - source: ./ida-accounts/server-files/default
    destination: /etc/nginx/sites-enabled/

hooks:
  BeforeInstall:
    - location: ./ida-accounts/scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./ida-accounts/scripts/application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./ida-accounts/scripts/application_start.sh
      timeout: 300
      runas: root