version: 0.2

phases:
  install:
    commands:
      - echo Initalling source NPM depencies
      - yarn
  pre_build:
    commands:
      - npm nx --version

  build:
    commands:
      - echo Projects build started on `date`
      - echo Using variables
      - echo NODE_ENV = $NODE_ENV

      # Run Tests
      # - echo Backend build started on `date`
      # - npm run test:gt:runs

      # Building backend
      - echo Backend build started on `date`
      - yarn build

      - echo Backend build completed on `date`

      # Creating deploy folder
      - mkdir ida-accounts
      
      # populate dist into deploy folder
      - mkdir ida-accounts/dist
      - cp -r dist/* ida-accounts/dist/
      
      # Populate scripts into deploy folder
      - mkdir ida-accounts/scripts
      - cp -r deploy/scripts/* ida-accounts/scripts/
    
      # Populate server files into deploy folder
      - mkdir ida-accounts/server-files
      - cp -r deploy/files/nginx.config ida-accounts/server-files/default

      - perl -pi -e "s/__SERVER_NAME__/$SERVER_NAME/g; s/__SSL_CERTIFICATE__/$SSL_CERTIFICATE/g; s/__SSL_CERTIFICATE_KEY__/$SSL_CERTIFICATE_KEY/g "  ida-accounts/server-files/default
      
      # Get config files
      - cp package.json ./ida-accounts/package.json
      - cp appspec.yml ./ida-accounts/appspec.yml
      - echo $NX_API_URL >> test.txt
      - echo $NX_SOCKET_API >> test.txt
      # Delete node_modules
      - rm -rf node_modules

      # List backck and frontend folders
      - ls ./ida-accounts

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    athentication:
      files:
        - '**/*'
      base-directory: ida-accounts
    blah:
      files:
        - '**/*'
      base-directory: ida-accounts
